### ISSUE TITLE
Document need for client.js

### ISSUE THREAD

**Issue by skpy** [jjdelc/grumble#3]
A fresh installation of Grumble failed to display a login prompt for me.  Using my browser's debugger, I saw that it was complaining about not finding a `client.js` file.  I `curl`ed the file from your example site to see what its contents needed to be.

Can you please update the documentation to indicate the need to create this file, and what its contents should be?

**Comment by jjdelc** [comment]
Added more info on the readme https://github.com/jjdelc/grumble/commit/558629c8f66a068114bed55861a3a76a06de4c52
